name: Run Python Tests
description: 'Run Python Tests'

inputs:
  codecov_token:
    description: 'CodeCov access token'
    required: true
  package_name:
    description: 'Package name for coverage'
    required: true
  BROWSERLESS__API_KEY:
    description: 'BROWSERLESS__API_KEY'
    required: true


runs:
    using: 'composite'
    steps:
      - name: Run tests with pytest (with coverage)
        shell: bash
        run: |
          coverage run --source=${{ inputs.package_name }} -m pytest -v -s --durations=0 --ignore=tests_* tests
        env:
          BROWSERLESS__API_KEY: ${{ inputs.BROWSERLESS__API_KEY         }}
      - name: Print coverage report
        shell: bash
        run: |
          coverage report -m
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN         : ${{ inputs.codecov_token         }}