
name       : Checkout Code from GitHub
description: 'Checkout Code from GitHub'

runs:
    using: 'composite'
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x