name       : Install Dependencies
description: 'Install Dependencies'

runs:
    using: 'composite'
    steps:
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
              ${{ runner.os }}-pip-
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

#      - name: Configure Playwright
#        shell: bash
#        run: |
#          playwright install chromium