name       : Run Unit Tests
on:
  push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Unit Tests
        uses: ./.github/actions/run-unit-tests
        with:
          codecov_token         : ${{ secrets.CODECOV_TOKEN         }}
          package_name          : ${{ secrets.PACKAGE_NAME          }}
          BROWSERLESS__API_KEY  : ${{ secrets.BROWSERLESS__API_KEY  }}
          AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION    : ${{ secrets.AWS_DEFAULT_REGION    }}
          AWS_ACCOUNT_ID        : ${{ secrets.AWS_ACCOUNT_ID        }}
          AWS_ACCESS_KEY_ID     : ${{ secrets.AWS_ACCESS_KEY_ID     }}

